spring:
  application:
    name: project-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs
