services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
#      - ./initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - microservices-network

  cloud-config:
    build: ./CloudConfig
    ports:
      - "8888:8888"
    environment:
      SERVER_PORT: 8888
    networks:
      - microservices-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api-gateway:
    build: ./ApiGateway
    environment:
      SERVER_PORT: 8080
      CLOUD_CONFIG_URL: http://cloud-config:8888
      USER_SERVICE: http://user-manager-service:8001
      TASK_SERVICE: http://task-manager-service:8002
      PROJECT_SERVICE: http://project-manager-service:8003
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  user-manager-service:
    build: ./UserManagementService
    ports:
      - "8001:8001"
    environment:
      SERVER_PORT: 8001
      CLOUD_CONFIG_URL: http://cloud-config:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
      - cloud-config
    networks:
      - microservices-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  task-manager-service:
    build: ./TaskManagementService
    ports:
      - "8002:8002"
    environment:
      SERVER_PORT: 8002
      CLOUD_CONFIG_URL: http://cloud-config:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
      - cloud-config
    networks:
      - microservices-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  project-manager-service:
    build: ./ProjectManagementService
    ports:
      - "8003:8003"
    environment:
      SERVER_PORT: 8003
      CLOUD_CONFIG_URL: http://cloud-config:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
      - cloud-config
    networks:
      - microservices-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Analytics Service
#  analytics-service:
#    image: analytics-service:latest
#    build: ./analytics-service
#    ports:
#      - "8004:8004"
#    environment:
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-analytics:5432/analytics_db
#      SPRING_DATASOURCE_USERNAME: analytics_user
#      SPRING_DATASOURCE_PASSWORD: your_password
#      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    depends_on:
#      - config-server
#      - postgres-analytics
#      - kafka
#    networks:
#      - microservices-network

  # Kafka
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - microservices-network

  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - microservices-network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - microservices-network

  # Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.9
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"  # Порт для приема логов
    depends_on:
      - elasticsearch
    networks:
      - microservices-network

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - microservices-network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - microservices-network

  # Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - microservices-network

volumes:
  postgres_data:
  elasticsearch-data:

networks:
  microservices-network:
    driver: bridge
