global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'task-manager-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['task-manager-service:8001']

  - job_name: 'project-manager-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['project-manager-service:8002']

  - job_name: 'user-manager-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'user-manager-service:8003' ]

