server:
  port: ${SERVER_PORT:5050}

logging:
  config: classpath:${logback:logback-spring.xml}

spring:
  application:
    name: api-gateway
  profiles:
    active: default
  config:
    import: configserver:${CLOUD_CONFIG_URL:http://localhost:5555}
  cloud:
    config:
      retry:
        max-attempts: 10
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 10000
      fail-fast: true


