server:
  port: ${SERVER_PORT:5050}

spring:
  application:
    name: api-gateway
  config:
    import: configserver:${CLOUD_CONFIG_URL:http://localhost:5555}
  cloud:
    config:
      retry:
        max-attempts: 10
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 10000
      fail-fast: true
    gateway:
      routes:
        - id: auth-manager
          uri: ${USER_SERVICE:http://localhost:5001}
          predicates:
            - Path=/api/auth/**
          filters:
            - LogFilter

        - id: user-manager
          uri: ${USER_SERVICE:http://localhost:5001}
          predicates:
            - Path=/api/users/**
          filters:
            - LogFilter

        - id: task-manager
          uri: ${TASK_SERVICE:http://localhost:5002}
          predicates:
            - Path=/api/tasks/**
          filters:
            - LogFilter

        - id: project-manager
          uri: ${PROJECT_SERVICE:http://localhost:5003}
          predicates:
            - Path=/api/projects/**
          filters:
            - LogFilter

#          - id: analytics-service
#            uri: http://analytics-service:8084
#            predicates:
#              - Path=/api/analytics/**
#            filters:
#              - StripPrefix=2
#              - name: RequestRateLimiter
#                args:
#                  redis-rate-limiter.replenishRate: 10
#                  redis-rate-limiter.burstCapacity: 20
#              - LoggingFilter

      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origin-patterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true