spring:
  application:
    name: project-service
  config:
    import: configserver:${CLOUD_CONFIG_URL:http://localhost:8888}
  cloud:
    config:
      retry:
        max-attempts: 10
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 10000
      fail-fast: true

server:
  port: ${SERVER_PORT:5002}

