server:
  port: ${SERVER_PORT:5004}

spring:
  application:
    name: analytics-service
  config:
    import: configserver:${CLOUD_CONFIG_URL:http://localhost:8888}
  cloud:
    config:
      retry:
        max-attempts: 10
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 10000
      fail-fast: true
  kafka:
    bootstrap-servers:
      - ${KAFKA_URL:localhost:9092}
    consumer:
      group-id: analytics-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ru.itmo.apiobjects.kafka.model
#        spring.json.value.default.type: ru.itmo.apiobjects.kafka.model.TaskRequest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:postgresql://${APP_POSTGRESQL_HOST:127.0.0.1}:${APP_POSTGRESQL_PORT:5432}/${APP_POSTGRESQL_NAME:analytics_db}
    username: ${APP_POSTGRESQL_USER:postgres}
    password: ${APP_POSTGRESQL_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  config: classpath:${logback:logback-spring.xml}
