spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: task-manager-service

server:
  port: 5053

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]

  endpoint:
    prometheus:
      access: unrestricted

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs
