server:
  port: ${SERVER_PORT:5555}

spring:
  profiles:
    active: native

  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config
            - classpath:/config/{application}
            - classpath:/config/{application}/{profile}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true


logging:
  config: classpath:${logback:logback-spring.xml}